name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore server/MobTimer.sln
    - name: Build
      run: dotnet build server/MobTimer.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test server/MobTimer.sln --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o release server/MobTimer.Web/MobTimer.Web.csproj
    - name: Package Artifacts
      uses: thedoctor0/zip-release@v0.3.0
      with:
        filename: release.zip
        path: release
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: release.zip
